//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrrSys.DataInterface.DataContract
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "FinalizeProductAchievementResponse", Namespace = "http://schemas.datacontract.org/2004/07/OrrSys.DataInterface.DataContract")]
    public partial class FinalizeProductAchievementResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private long JdeBatchNumberField;

        private decimal JdeDateField;

        private uint JdeTimeField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long JdeBatchNumber
        {
            get
            {
                return this.JdeBatchNumberField;
            }
            set
            {
                this.JdeBatchNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal JdeDate
        {
            get
            {
                return this.JdeDateField;
            }
            set
            {
                this.JdeDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint JdeTime
        {
            get
            {
                return this.JdeTimeField;
            }
            set
            {
                this.JdeTimeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ProductionOrderStatusResponse", Namespace = "http://schemas.datacontract.org/2004/07/OrrSys.DataInterface.DataContract")]
    public partial class ProductionOrderStatusResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private OrrSys.DataInterface.DataContract.ProductionOrderStatus[] PayloadField;

        private string ProductionOrderIdField;

        private string SagaReferenceIdField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrrSys.DataInterface.DataContract.ProductionOrderStatus[] Payload
        {
            get
            {
                return this.PayloadField;
            }
            set
            {
                this.PayloadField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductionOrderId
        {
            get
            {
                return this.ProductionOrderIdField;
            }
            set
            {
                this.ProductionOrderIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SagaReferenceId
        {
            get
            {
                return this.SagaReferenceIdField;
            }
            set
            {
                this.SagaReferenceIdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ProductionOrderStatus", Namespace = "http://schemas.datacontract.org/2004/07/OrrSys.DataInterface.DataContract")]
    public partial class ProductionOrderStatus : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CompleteFlagField;

        private System.DateTime FinishDateField;

        private System.Nullable<double> OrderQuantityField;

        private string OrderQuantityUomField;

        private string ProductionOrderNumberField;

        private string ReleaseFlagField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompleteFlag
        {
            get
            {
                return this.CompleteFlagField;
            }
            set
            {
                this.CompleteFlagField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FinishDate
        {
            get
            {
                return this.FinishDateField;
            }
            set
            {
                this.FinishDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> OrderQuantity
        {
            get
            {
                return this.OrderQuantityField;
            }
            set
            {
                this.OrderQuantityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderQuantityUom
        {
            get
            {
                return this.OrderQuantityUomField;
            }
            set
            {
                this.OrderQuantityUomField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductionOrderNumber
        {
            get
            {
                return this.ProductionOrderNumberField;
            }
            set
            {
                this.ProductionOrderNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReleaseFlag
        {
            get
            {
                return this.ReleaseFlagField;
            }
            set
            {
                this.ReleaseFlagField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MaterialMasterUpdateRequest", Namespace = "http://schemas.datacontract.org/2004/07/OrrSys.DataInterface.DataContract")]
    public partial class MaterialMasterUpdateRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private OrrSys.DataInterface.DataContract.MaterialMasterUpdate[] MaterialMasterUpdateArrayField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrrSys.DataInterface.DataContract.MaterialMasterUpdate[] MaterialMasterUpdateArray
        {
            get
            {
                return this.MaterialMasterUpdateArrayField;
            }
            set
            {
                this.MaterialMasterUpdateArrayField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MaterialMasterUpdate", Namespace = "http://schemas.datacontract.org/2004/07/OrrSys.DataInterface.DataContract")]
    public partial class MaterialMasterUpdate : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string OldMaterialNumberField;

        private string PrimeGtinField;

        private string RejectCodeField;

        private string RejectGtinField;

        private string SapDescription0Field;

        private string SapDescription1Field;

        private string SapMaterialNumberField;

        private string SprasIsoLanguage0Field;

        private string SprasIsoLanguage1Field;

        private string SprasLanguage0Field;

        private string SprasLanguage1Field;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldMaterialNumber
        {
            get
            {
                return this.OldMaterialNumberField;
            }
            set
            {
                this.OldMaterialNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimeGtin
        {
            get
            {
                return this.PrimeGtinField;
            }
            set
            {
                this.PrimeGtinField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RejectCode
        {
            get
            {
                return this.RejectCodeField;
            }
            set
            {
                this.RejectCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RejectGtin
        {
            get
            {
                return this.RejectGtinField;
            }
            set
            {
                this.RejectGtinField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SapDescription0
        {
            get
            {
                return this.SapDescription0Field;
            }
            set
            {
                this.SapDescription0Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SapDescription1
        {
            get
            {
                return this.SapDescription1Field;
            }
            set
            {
                this.SapDescription1Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SapMaterialNumber
        {
            get
            {
                return this.SapMaterialNumberField;
            }
            set
            {
                this.SapMaterialNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SprasIsoLanguage0
        {
            get
            {
                return this.SprasIsoLanguage0Field;
            }
            set
            {
                this.SprasIsoLanguage0Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SprasIsoLanguage1
        {
            get
            {
                return this.SprasIsoLanguage1Field;
            }
            set
            {
                this.SprasIsoLanguage1Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SprasLanguage0
        {
            get
            {
                return this.SprasLanguage0Field;
            }
            set
            {
                this.SprasLanguage0Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SprasLanguage1
        {
            get
            {
                return this.SprasLanguage1Field;
            }
            set
            {
                this.SprasLanguage1Field = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "WorkOrderCompletionRequest", Namespace = "http://schemas.datacontract.org/2004/07/OrrSys.DataInterface.DataContract")]
    public partial class WorkOrderCompletionRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private OrrSys.DataInterface.DataContract.F3111Z1[] F3111Z1ArrayField;

        private OrrSys.DataInterface.DataContract.F3112Z1 F3112Z1Field;

        private OrrSys.DataInterface.DataContract.F4801Z1 F4801Z1Field;

        private OrrSys.DataInterface.DataContract.LabelDetail LabelDetailField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrrSys.DataInterface.DataContract.F3111Z1[] F3111Z1Array
        {
            get
            {
                return this.F3111Z1ArrayField;
            }
            set
            {
                this.F3111Z1ArrayField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrrSys.DataInterface.DataContract.F3112Z1 F3112Z1
        {
            get
            {
                return this.F3112Z1Field;
            }
            set
            {
                this.F3112Z1Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrrSys.DataInterface.DataContract.F4801Z1 F4801Z1
        {
            get
            {
                return this.F4801Z1Field;
            }
            set
            {
                this.F4801Z1Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrrSys.DataInterface.DataContract.LabelDetail LabelDetail
        {
            get
            {
                return this.LabelDetailField;
            }
            set
            {
                this.LabelDetailField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "F3112Z1", Namespace = "http://schemas.datacontract.org/2004/07/OrrSys.DataInterface.DataContract")]
    public partial class F3112Z1 : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string SzaldField;

        private string SzdctoField;

        private System.Nullable<int> SzdocoField;

        private System.Nullable<int> SzkitField;

        private string SzkitaField;

        private string SzkitlField;

        private string SzmmcuField;

        private System.Nullable<double> SzsoqsField;

        private string SztrtField;

        private string SzuomField;

        private string SzurcdField;

        private string SzurrfField;

        private string SzwmcuField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Szald
        {
            get
            {
                return this.SzaldField;
            }
            set
            {
                this.SzaldField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Szdcto
        {
            get
            {
                return this.SzdctoField;
            }
            set
            {
                this.SzdctoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Szdoco
        {
            get
            {
                return this.SzdocoField;
            }
            set
            {
                this.SzdocoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Szkit
        {
            get
            {
                return this.SzkitField;
            }
            set
            {
                this.SzkitField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Szkita
        {
            get
            {
                return this.SzkitaField;
            }
            set
            {
                this.SzkitaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Szkitl
        {
            get
            {
                return this.SzkitlField;
            }
            set
            {
                this.SzkitlField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Szmmcu
        {
            get
            {
                return this.SzmmcuField;
            }
            set
            {
                this.SzmmcuField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Szsoqs
        {
            get
            {
                return this.SzsoqsField;
            }
            set
            {
                this.SzsoqsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sztrt
        {
            get
            {
                return this.SztrtField;
            }
            set
            {
                this.SztrtField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Szuom
        {
            get
            {
                return this.SzuomField;
            }
            set
            {
                this.SzuomField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Szurcd
        {
            get
            {
                return this.SzurcdField;
            }
            set
            {
                this.SzurcdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Szurrf
        {
            get
            {
                return this.SzurrfField;
            }
            set
            {
                this.SzurrfField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Szwmcu
        {
            get
            {
                return this.SzwmcuField;
            }
            set
            {
                this.SzwmcuField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "F4801Z1", Namespace = "http://schemas.datacontract.org/2004/07/OrrSys.DataInterface.DataContract")]
    public partial class F4801Z1 : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private char JdeStockingTypeField;

        private string PartPackField;

        private string SapMaterialNumberField;

        private string SyaitmField;

        private string SydctoField;

        private System.Nullable<double> SydocoField;

        private System.Nullable<double> SyitmField;

        private string SylitmField;

        private string SylocnField;

        private string Sylot2Field;

        private string SylotnField;

        private System.Nullable<char> SylotsField;

        private string SymcuField;

        private string SymmcuField;

        private string SyrcdField;

        private System.Nullable<double> SysoqsField;

        private string SyuomField;

        private string Syvr01Field;

        private string Syvr02Field;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public char JdeStockingType
        {
            get
            {
                return this.JdeStockingTypeField;
            }
            set
            {
                this.JdeStockingTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartPack
        {
            get
            {
                return this.PartPackField;
            }
            set
            {
                this.PartPackField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SapMaterialNumber
        {
            get
            {
                return this.SapMaterialNumberField;
            }
            set
            {
                this.SapMaterialNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Syaitm
        {
            get
            {
                return this.SyaitmField;
            }
            set
            {
                this.SyaitmField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sydcto
        {
            get
            {
                return this.SydctoField;
            }
            set
            {
                this.SydctoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Sydoco
        {
            get
            {
                return this.SydocoField;
            }
            set
            {
                this.SydocoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Syitm
        {
            get
            {
                return this.SyitmField;
            }
            set
            {
                this.SyitmField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sylitm
        {
            get
            {
                return this.SylitmField;
            }
            set
            {
                this.SylitmField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sylocn
        {
            get
            {
                return this.SylocnField;
            }
            set
            {
                this.SylocnField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sylot2
        {
            get
            {
                return this.Sylot2Field;
            }
            set
            {
                this.Sylot2Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sylotn
        {
            get
            {
                return this.SylotnField;
            }
            set
            {
                this.SylotnField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<char> Sylots
        {
            get
            {
                return this.SylotsField;
            }
            set
            {
                this.SylotsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symcu
        {
            get
            {
                return this.SymcuField;
            }
            set
            {
                this.SymcuField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symmcu
        {
            get
            {
                return this.SymmcuField;
            }
            set
            {
                this.SymmcuField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Syrcd
        {
            get
            {
                return this.SyrcdField;
            }
            set
            {
                this.SyrcdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Sysoqs
        {
            get
            {
                return this.SysoqsField;
            }
            set
            {
                this.SysoqsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Syuom
        {
            get
            {
                return this.SyuomField;
            }
            set
            {
                this.SyuomField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Syvr01
        {
            get
            {
                return this.Syvr01Field;
            }
            set
            {
                this.Syvr01Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Syvr02
        {
            get
            {
                return this.Syvr02Field;
            }
            set
            {
                this.Syvr02Field = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "LabelDetail", Namespace = "http://schemas.datacontract.org/2004/07/OrrSys.DataInterface.DataContract")]
    public partial class LabelDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string AcrsCertField;

        private System.DateTime DateLastAccessedField;

        private string GtinField;

        private string ItemField;

        private string ItemDescriptionField;

        private int ItemLengthField;

        private System.DateTime LabelDateField;

        private string LabelNameField;

        private System.TimeSpan LabelTimeField;

        private string LabelValueField;

        private string LotNumberField;

        private string LotStatusField;

        private string OtherInfoField;

        private string PrinterNameField;

        private string ProductGradeField;

        private int QuantityField;

        private string StandardField;

        private int WeightField;

        private int WorkOrderField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcrsCert
        {
            get
            {
                return this.AcrsCertField;
            }
            set
            {
                this.AcrsCertField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateLastAccessed
        {
            get
            {
                return this.DateLastAccessedField;
            }
            set
            {
                this.DateLastAccessedField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gtin
        {
            get
            {
                return this.GtinField;
            }
            set
            {
                this.GtinField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item
        {
            get
            {
                return this.ItemField;
            }
            set
            {
                this.ItemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemDescription
        {
            get
            {
                return this.ItemDescriptionField;
            }
            set
            {
                this.ItemDescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemLength
        {
            get
            {
                return this.ItemLengthField;
            }
            set
            {
                this.ItemLengthField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LabelDate
        {
            get
            {
                return this.LabelDateField;
            }
            set
            {
                this.LabelDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LabelName
        {
            get
            {
                return this.LabelNameField;
            }
            set
            {
                this.LabelNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan LabelTime
        {
            get
            {
                return this.LabelTimeField;
            }
            set
            {
                this.LabelTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LabelValue
        {
            get
            {
                return this.LabelValueField;
            }
            set
            {
                this.LabelValueField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LotNumber
        {
            get
            {
                return this.LotNumberField;
            }
            set
            {
                this.LotNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LotStatus
        {
            get
            {
                return this.LotStatusField;
            }
            set
            {
                this.LotStatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtherInfo
        {
            get
            {
                return this.OtherInfoField;
            }
            set
            {
                this.OtherInfoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrinterName
        {
            get
            {
                return this.PrinterNameField;
            }
            set
            {
                this.PrinterNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductGrade
        {
            get
            {
                return this.ProductGradeField;
            }
            set
            {
                this.ProductGradeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Standard
        {
            get
            {
                return this.StandardField;
            }
            set
            {
                this.StandardField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Weight
        {
            get
            {
                return this.WeightField;
            }
            set
            {
                this.WeightField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WorkOrder
        {
            get
            {
                return this.WorkOrderField;
            }
            set
            {
                this.WorkOrderField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "F3111Z1", Namespace = "http://schemas.datacontract.org/2004/07/OrrSys.DataInterface.DataContract")]
    public partial class F3111Z1 : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string SzcmcuField;

        private string SzcpilField;

        private int SzcpitField;

        private string SzdctoField;

        private int SzdocoField;

        private string SzlocnField;

        private string SzlotnField;

        private string SzmcuField;

        private System.Nullable<int> SztrqtField;

        private string SzumField;

        private int SzuorgField;

        private string SzurrfField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Szcmcu
        {
            get
            {
                return this.SzcmcuField;
            }
            set
            {
                this.SzcmcuField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Szcpil
        {
            get
            {
                return this.SzcpilField;
            }
            set
            {
                this.SzcpilField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Szcpit
        {
            get
            {
                return this.SzcpitField;
            }
            set
            {
                this.SzcpitField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Szdcto
        {
            get
            {
                return this.SzdctoField;
            }
            set
            {
                this.SzdctoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Szdoco
        {
            get
            {
                return this.SzdocoField;
            }
            set
            {
                this.SzdocoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Szlocn
        {
            get
            {
                return this.SzlocnField;
            }
            set
            {
                this.SzlocnField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Szlotn
        {
            get
            {
                return this.SzlotnField;
            }
            set
            {
                this.SzlotnField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Szmcu
        {
            get
            {
                return this.SzmcuField;
            }
            set
            {
                this.SzmcuField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sztrqt
        {
            get
            {
                return this.SztrqtField;
            }
            set
            {
                this.SztrqtField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Szum
        {
            get
            {
                return this.SzumField;
            }
            set
            {
                this.SzumField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Szuorg
        {
            get
            {
                return this.SzuorgField;
            }
            set
            {
                this.SzuorgField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Szurrf
        {
            get
            {
                return this.SzurrfField;
            }
            set
            {
                this.SzurrfField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "WorkOrderCompletionResponse", Namespace = "http://schemas.datacontract.org/2004/07/OrrSys.DataInterface.DataContract")]
    public partial class WorkOrderCompletionResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string ItemNumberField;

        private string LotNumberField;

        private string WorkOrderField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemNumber
        {
            get
            {
                return this.ItemNumberField;
            }
            set
            {
                this.ItemNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LotNumber
        {
            get
            {
                return this.LotNumberField;
            }
            set
            {
                this.LotNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkOrder
        {
            get
            {
                return this.WorkOrderField;
            }
            set
            {
                this.WorkOrderField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IDataInterfacingService")]
public interface IDataInterfacingService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDataInterfacingService/FinalizeProductAchievement", ReplyAction = "http://tempuri.org/IDataInterfacingService/FinalizeProductAchievementResponse")]
    OrrSys.DataInterface.DataContract.FinalizeProductAchievementResponse FinalizeProductAchievement(string lotNumber);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDataInterfacingService/RetrieveProductionOrdresStatusLongSequ" +
        "ence", ReplyAction = "http://tempuri.org/IDataInterfacingService/RetrieveProductionOrdresStatusLongSequ" +
        "enceResponse")]
    OrrSys.DataInterface.DataContract.ProductionOrderStatusResponse RetrieveProductionOrdresStatusLongSequence();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDataInterfacingService/RetrieveProductionOrdresStatusShortSeq" +
        "uence", ReplyAction = "http://tempuri.org/IDataInterfacingService/RetrieveProductionOrdresStatusShortSeq" +
        "uenceResponse")]
    OrrSys.DataInterface.DataContract.ProductionOrderStatusResponse RetrieveProductionOrdresStatusShortSequence();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDataInterfacingService/UpdateMaterialMaster", ReplyAction = "http://tempuri.org/IDataInterfacingService/UpdateMaterialMasterResponse")]
    void UpdateMaterialMaster(OrrSys.DataInterface.DataContract.MaterialMasterUpdateRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDataInterfacingService/CompleteWorkOrder", ReplyAction = "http://tempuri.org/IDataInterfacingService/CompleteWorkOrderResponse")]
    OrrSys.DataInterface.DataContract.WorkOrderCompletionResponse CompleteWorkOrder(OrrSys.DataInterface.DataContract.WorkOrderCompletionRequest request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDataInterfacingServiceChannel : IDataInterfacingService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DataInterfacingServiceClient : System.ServiceModel.ClientBase<IDataInterfacingService>, IDataInterfacingService
{

    public DataInterfacingServiceClient()
    {
    }

    public DataInterfacingServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public DataInterfacingServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public DataInterfacingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public DataInterfacingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public OrrSys.DataInterface.DataContract.FinalizeProductAchievementResponse FinalizeProductAchievement(string lotNumber)
    {
        return base.Channel.FinalizeProductAchievement(lotNumber);
    }

    public OrrSys.DataInterface.DataContract.ProductionOrderStatusResponse RetrieveProductionOrdresStatusLongSequence()
    {
        return base.Channel.RetrieveProductionOrdresStatusLongSequence();
    }

    public OrrSys.DataInterface.DataContract.ProductionOrderStatusResponse RetrieveProductionOrdresStatusShortSequence()
    {
        return base.Channel.RetrieveProductionOrdresStatusShortSequence();
    }

    public void UpdateMaterialMaster(OrrSys.DataInterface.DataContract.MaterialMasterUpdateRequest request)
    {
        base.Channel.UpdateMaterialMaster(request);
    }

    public OrrSys.DataInterface.DataContract.WorkOrderCompletionResponse CompleteWorkOrder(OrrSys.DataInterface.DataContract.WorkOrderCompletionRequest request)
    {
        return base.Channel.CompleteWorkOrder(request);
    }
}