// CRITICAL: Do not change the location of this files. It is duplicated in the Test-Harness. //
// CRITICAl: Do not change the namespace of any code within this file in any way. //

    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.18444
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "sap-com:XI.interfaces:financials", ConfigurationName = "ZMBGMCR02_EXTND_OB_Async_MI")]
    public interface ZMBGMCR02_EXTND_OB_Async_MI
    {

        // CODEGEN: Generating message contract since the operation ZMBGMCR02_EXTND_OB_Async_MI is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://sap.com/xi/WebService/soap1.1")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void ZMBGMCR02_EXTND_OB_Async_MI(ZMBGMCR02_EXTND_OB_Async_MI1 request);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, AsyncPattern = true, Action = "http://sap.com/xi/WebService/soap1.1")]
        System.IAsyncResult BeginZMBGMCR02_EXTND_OB_Async_MI(ZMBGMCR02_EXTND_OB_Async_MI1 request, System.AsyncCallback callback, object asyncState);

        void EndZMBGMCR02_EXTND_OB_Async_MI(System.IAsyncResult result);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ZMBGMCR02_EXTND
    {

        private ZMBGMCRZMBGMCR02_EXTND iDOCField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public ZMBGMCRZMBGMCR02_EXTND IDOC
        {
            get
            {
                return this.iDOCField;
            }
            set
            {
                this.iDOCField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "ZMBGMCR.ZMBGMCR02_EXTND")]
    public partial class ZMBGMCRZMBGMCR02_EXTND
    {

        private EDI_DC40ZMBGMCRZMBGMCR02_EXTND eDI_DC40Field;

        private ZMBGMCR02_EXTNDE1MBGMCR e1MBGMCRField;

        private ZMBGMCR02_EXTNDE1BP2017_GM_HEAD_01 e1BP2017_GM_HEAD_01Field;

        private ZMBGMCR02_EXTNDE1BP2017_GM_CODE e1BP2017_GM_CODEField;

        private ZMBGMCR02_EXTNDE1BP2017_GM_ITEM_CREATE[] e1BP2017_GM_ITEM_CREATEField;

        private ZMBGMCR02_EXTNDE1BP2017_GM_SERIALNUMBER[] e1BP2017_GM_SERIALNUMBERField;

        private string bEGINField;

        public ZMBGMCRZMBGMCR02_EXTND()
        {
            this.bEGINField = "1";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public EDI_DC40ZMBGMCRZMBGMCR02_EXTND EDI_DC40
        {
            get
            {
                return this.eDI_DC40Field;
            }
            set
            {
                this.eDI_DC40Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public ZMBGMCR02_EXTNDE1MBGMCR E1MBGMCR
        {
            get
            {
                return this.e1MBGMCRField;
            }
            set
            {
                this.e1MBGMCRField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public ZMBGMCR02_EXTNDE1BP2017_GM_HEAD_01 E1BP2017_GM_HEAD_01
        {
            get
            {
                return this.e1BP2017_GM_HEAD_01Field;
            }
            set
            {
                this.e1BP2017_GM_HEAD_01Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public ZMBGMCR02_EXTNDE1BP2017_GM_CODE E1BP2017_GM_CODE
        {
            get
            {
                return this.e1BP2017_GM_CODEField;
            }
            set
            {
                this.e1BP2017_GM_CODEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("E1BP2017_GM_ITEM_CREATE", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public ZMBGMCR02_EXTNDE1BP2017_GM_ITEM_CREATE[] E1BP2017_GM_ITEM_CREATE
        {
            get
            {
                return this.e1BP2017_GM_ITEM_CREATEField;
            }
            set
            {
                this.e1BP2017_GM_ITEM_CREATEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("E1BP2017_GM_SERIALNUMBER", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public ZMBGMCR02_EXTNDE1BP2017_GM_SERIALNUMBER[] E1BP2017_GM_SERIALNUMBER
        {
            get
            {
                return this.e1BP2017_GM_SERIALNUMBERField;
            }
            set
            {
                this.e1BP2017_GM_SERIALNUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BEGIN
        {
            get
            {
                return this.bEGINField;
            }
            set
            {
                this.bEGINField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "EDI_DC40.ZMBGMCR.ZMBGMCR02_EXTND")]
    public partial class EDI_DC40ZMBGMCRZMBGMCR02_EXTND
    {

        private string tABNAMField;

        private string mANDTField;

        private string dOCNUMField;

        private string dOCRELField;

        private string sTATUSField;

        private EDI_DC40ZMBGMCRZMBGMCR02_EXTNDDIRECT dIRECTField;

        private string oUTMODField;

        private string eXPRSSField;

        private string tESTField;

        private string iDOCTYPField;

        private string cIMTYPField;

        private string mESTYPField;

        private string mESCODField;

        private string mESFCTField;

        private string sTDField;

        private string sTDVRSField;

        private string sTDMESField;

        private string sNDPORField;

        private string sNDPRTField;

        private string sNDPFCField;

        private string sNDPRNField;

        private string sNDSADField;

        private string sNDLADField;

        private string rCVPORField;

        private string rCVPRTField;

        private string rCVPFCField;

        private string rCVPRNField;

        private string rCVSADField;

        private string rCVLADField;

        private string cREDATField;

        private string cRETIMField;

        private string rEFINTField;

        private string rEFGRPField;

        private string rEFMESField;

        private string aRCKEYField;

        private string sERIALField;

        private string sEGMENTField;

        public EDI_DC40ZMBGMCRZMBGMCR02_EXTND()
        {
            this.tABNAMField = "EDI_DC40";
            this.iDOCTYPField = "ZMBGMCR02_EXTND";
            this.mESTYPField = "ZMBGMCR";
            this.sEGMENTField = "1";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string TABNAM
        {
            get
            {
                return this.tABNAMField;
            }
            set
            {
                this.tABNAMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string MANDT
        {
            get
            {
                return this.mANDTField;
            }
            set
            {
                this.mANDTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string DOCNUM
        {
            get
            {
                return this.dOCNUMField;
            }
            set
            {
                this.dOCNUMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string DOCREL
        {
            get
            {
                return this.dOCRELField;
            }
            set
            {
                this.dOCRELField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string STATUS
        {
            get
            {
                return this.sTATUSField;
            }
            set
            {
                this.sTATUSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public EDI_DC40ZMBGMCRZMBGMCR02_EXTNDDIRECT DIRECT
        {
            get
            {
                return this.dIRECTField;
            }
            set
            {
                this.dIRECTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string OUTMOD
        {
            get
            {
                return this.oUTMODField;
            }
            set
            {
                this.oUTMODField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string EXPRSS
        {
            get
            {
                return this.eXPRSSField;
            }
            set
            {
                this.eXPRSSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string TEST
        {
            get
            {
                return this.tESTField;
            }
            set
            {
                this.tESTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public string IDOCTYP
        {
            get
            {
                return this.iDOCTYPField;
            }
            set
            {
                this.iDOCTYPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public string CIMTYP
        {
            get
            {
                return this.cIMTYPField;
            }
            set
            {
                this.cIMTYPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public string MESTYP
        {
            get
            {
                return this.mESTYPField;
            }
            set
            {
                this.mESTYPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public string MESCOD
        {
            get
            {
                return this.mESCODField;
            }
            set
            {
                this.mESCODField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
        public string MESFCT
        {
            get
            {
                return this.mESFCTField;
            }
            set
            {
                this.mESFCTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 14)]
        public string STD
        {
            get
            {
                return this.sTDField;
            }
            set
            {
                this.sTDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 15)]
        public string STDVRS
        {
            get
            {
                return this.sTDVRSField;
            }
            set
            {
                this.sTDVRSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 16)]
        public string STDMES
        {
            get
            {
                return this.sTDMESField;
            }
            set
            {
                this.sTDMESField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 17)]
        public string SNDPOR
        {
            get
            {
                return this.sNDPORField;
            }
            set
            {
                this.sNDPORField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 18)]
        public string SNDPRT
        {
            get
            {
                return this.sNDPRTField;
            }
            set
            {
                this.sNDPRTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 19)]
        public string SNDPFC
        {
            get
            {
                return this.sNDPFCField;
            }
            set
            {
                this.sNDPFCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 20)]
        public string SNDPRN
        {
            get
            {
                return this.sNDPRNField;
            }
            set
            {
                this.sNDPRNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 21)]
        public string SNDSAD
        {
            get
            {
                return this.sNDSADField;
            }
            set
            {
                this.sNDSADField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 22)]
        public string SNDLAD
        {
            get
            {
                return this.sNDLADField;
            }
            set
            {
                this.sNDLADField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 23)]
        public string RCVPOR
        {
            get
            {
                return this.rCVPORField;
            }
            set
            {
                this.rCVPORField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 24)]
        public string RCVPRT
        {
            get
            {
                return this.rCVPRTField;
            }
            set
            {
                this.rCVPRTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 25)]
        public string RCVPFC
        {
            get
            {
                return this.rCVPFCField;
            }
            set
            {
                this.rCVPFCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 26)]
        public string RCVPRN
        {
            get
            {
                return this.rCVPRNField;
            }
            set
            {
                this.rCVPRNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 27)]
        public string RCVSAD
        {
            get
            {
                return this.rCVSADField;
            }
            set
            {
                this.rCVSADField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 28)]
        public string RCVLAD
        {
            get
            {
                return this.rCVLADField;
            }
            set
            {
                this.rCVLADField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 29)]
        public string CREDAT
        {
            get
            {
                return this.cREDATField;
            }
            set
            {
                this.cREDATField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 30)]
        public string CRETIM
        {
            get
            {
                return this.cRETIMField;
            }
            set
            {
                this.cRETIMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 31)]
        public string REFINT
        {
            get
            {
                return this.rEFINTField;
            }
            set
            {
                this.rEFINTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 32)]
        public string REFGRP
        {
            get
            {
                return this.rEFGRPField;
            }
            set
            {
                this.rEFGRPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 33)]
        public string REFMES
        {
            get
            {
                return this.rEFMESField;
            }
            set
            {
                this.rEFMESField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 34)]
        public string ARCKEY
        {
            get
            {
                return this.aRCKEYField;
            }
            set
            {
                this.aRCKEYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 35)]
        public string SERIAL
        {
            get
            {
                return this.sERIALField;
            }
            set
            {
                this.sERIALField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SEGMENT
        {
            get
            {
                return this.sEGMENTField;
            }
            set
            {
                this.sEGMENTField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum EDI_DC40ZMBGMCRZMBGMCR02_EXTNDDIRECT
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "ZMBGMCR02_EXTND.E1BP2017_GM_SERIALNUMBER")]
    public partial class ZMBGMCR02_EXTNDE1BP2017_GM_SERIALNUMBER
    {

        private string mATDOC_ITMField;

        private string sERIALNOField;

        private string uIIField;

        private string sEGMENTField;

        public ZMBGMCR02_EXTNDE1BP2017_GM_SERIALNUMBER()
        {
            this.sEGMENTField = "1";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string MATDOC_ITM
        {
            get
            {
                return this.mATDOC_ITMField;
            }
            set
            {
                this.mATDOC_ITMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string SERIALNO
        {
            get
            {
                return this.sERIALNOField;
            }
            set
            {
                this.sERIALNOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string UII
        {
            get
            {
                return this.uIIField;
            }
            set
            {
                this.uIIField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SEGMENT
        {
            get
            {
                return this.sEGMENTField;
            }
            set
            {
                this.sEGMENTField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "ZMBGMCR02_EXTND.Z1MBGMCR_ITEM_EXTND")]
    public partial class ZMBGMCR02_EXTNDZ1MBGMCR_ITEM_EXTND
    {

        private string lOT_NUMBERField;

        private string sEGMENTField;

        public ZMBGMCR02_EXTNDZ1MBGMCR_ITEM_EXTND()
        {
            this.sEGMENTField = "1";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string LOT_NUMBER
        {
            get
            {
                return this.lOT_NUMBERField;
            }
            set
            {
                this.lOT_NUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SEGMENT
        {
            get
            {
                return this.sEGMENTField;
            }
            set
            {
                this.sEGMENTField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "ZMBGMCR02_EXTND.E1BP2017_GM_ITEM_CREATE1")]
    public partial class ZMBGMCR02_EXTNDE1BP2017_GM_ITEM_CREATE1
    {

        private string dELIV_NUMBField;

        private string dELIV_ITEMField;

        private string nB_SLIPSField;

        private string nB_SLIPSXField;

        private string gR_RCPTXField;

        private string uNLOAD_PTXField;

        private string sPEC_MVMTField;

        private string gRANT_NBRField;

        private string cMMT_ITEM_LONGField;

        private string fUNC_AREA_LONGField;

        private string lINE_IDField;

        private string pARENT_IDField;

        private string lINE_DEPTHField;

        private string qUANTITYField;

        private string bASE_UOMField;

        private string lONGNUMField;

        private string bUDGET_PERIODField;

        private string sEGMENTField;

        public ZMBGMCR02_EXTNDE1BP2017_GM_ITEM_CREATE1()
        {
            this.sEGMENTField = "1";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string DELIV_NUMB
        {
            get
            {
                return this.dELIV_NUMBField;
            }
            set
            {
                this.dELIV_NUMBField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string DELIV_ITEM
        {
            get
            {
                return this.dELIV_ITEMField;
            }
            set
            {
                this.dELIV_ITEMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string NB_SLIPS
        {
            get
            {
                return this.nB_SLIPSField;
            }
            set
            {
                this.nB_SLIPSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string NB_SLIPSX
        {
            get
            {
                return this.nB_SLIPSXField;
            }
            set
            {
                this.nB_SLIPSXField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string GR_RCPTX
        {
            get
            {
                return this.gR_RCPTXField;
            }
            set
            {
                this.gR_RCPTXField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string UNLOAD_PTX
        {
            get
            {
                return this.uNLOAD_PTXField;
            }
            set
            {
                this.uNLOAD_PTXField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string SPEC_MVMT
        {
            get
            {
                return this.sPEC_MVMTField;
            }
            set
            {
                this.sPEC_MVMTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string GRANT_NBR
        {
            get
            {
                return this.gRANT_NBRField;
            }
            set
            {
                this.gRANT_NBRField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string CMMT_ITEM_LONG
        {
            get
            {
                return this.cMMT_ITEM_LONGField;
            }
            set
            {
                this.cMMT_ITEM_LONGField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public string FUNC_AREA_LONG
        {
            get
            {
                return this.fUNC_AREA_LONGField;
            }
            set
            {
                this.fUNC_AREA_LONGField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public string LINE_ID
        {
            get
            {
                return this.lINE_IDField;
            }
            set
            {
                this.lINE_IDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public string PARENT_ID
        {
            get
            {
                return this.pARENT_IDField;
            }
            set
            {
                this.pARENT_IDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public string LINE_DEPTH
        {
            get
            {
                return this.lINE_DEPTHField;
            }
            set
            {
                this.lINE_DEPTHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
        public string QUANTITY
        {
            get
            {
                return this.qUANTITYField;
            }
            set
            {
                this.qUANTITYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 14)]
        public string BASE_UOM
        {
            get
            {
                return this.bASE_UOMField;
            }
            set
            {
                this.bASE_UOMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 15)]
        public string LONGNUM
        {
            get
            {
                return this.lONGNUMField;
            }
            set
            {
                this.lONGNUMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 16)]
        public string BUDGET_PERIOD
        {
            get
            {
                return this.bUDGET_PERIODField;
            }
            set
            {
                this.bUDGET_PERIODField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SEGMENT
        {
            get
            {
                return this.sEGMENTField;
            }
            set
            {
                this.sEGMENTField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "ZMBGMCR02_EXTND.E1BP2017_GM_ITEM_CREATE")]
    public partial class ZMBGMCR02_EXTNDE1BP2017_GM_ITEM_CREATE
    {

        private string mATERIALField;

        private string pLANTField;

        private string sTGE_LOCField;

        private string bATCHField;

        private string mOVE_TYPEField;

        private string sTCK_TYPEField;

        private string sPEC_STOCKField;

        private string vENDORField;

        private string cUSTOMERField;

        private string sALES_ORDField;

        private string s_ORD_ITEMField;

        private string sCHED_LINEField;

        private string vAL_TYPEField;

        private string eNTRY_QNTField;

        private string eNTRY_UOMField;

        private string eNTRY_UOM_ISOField;

        private string pO_PR_QNTField;

        private string oRDERPR_UNField;

        private string oRDERPR_UN_ISOField;

        private string pO_NUMBERField;

        private string pO_ITEMField;

        private string sHIPPINGField;

        private string cOMP_SHIPField;

        private string nO_MORE_GRField;

        private string iTEM_TEXTField;

        private string gR_RCPTField;

        private string uNLOAD_PTField;

        private string cOSTCENTERField;

        private string oRDERIDField;

        private string oRDER_ITNOField;

        private string cALC_MOTIVEField;

        private string aSSET_NOField;

        private string sUB_NUMBERField;

        private string rESERV_NOField;

        private string rES_ITEMField;

        private string rES_TYPEField;

        private string wITHDRAWNField;

        private string mOVE_MATField;

        private string mOVE_PLANTField;

        private string mOVE_STLOCField;

        private string mOVE_BATCHField;

        private string mOVE_VAL_TYPEField;

        private string mVT_INDField;

        private string mOVE_REASField;

        private string rL_EST_KEYField;

        private string rEF_DATEField;

        private string cOST_OBJField;

        private string pROFIT_SEGM_NOField;

        private string pROFIT_CTRField;

        private string wBS_ELEMField;

        private string nETWORKField;

        private string aCTIVITYField;

        private string pART_ACCTField;

        private string aMOUNT_LCField;

        private string aMOUNT_SVField;

        private string rEF_DOC_YRField;

        private string rEF_DOCField;

        private string rEF_DOC_ITField;

        private string eXPIRYDATEField;

        private string pROD_DATEField;

        private string fUNDField;

        private string fUNDS_CTRField;

        private string cMMT_ITEMField;

        private string vAL_SALES_ORDField;

        private string vAL_S_ORD_ITEMField;

        private string vAL_WBS_ELEMField;

        private string gL_ACCOUNTField;

        private string iND_PROPOSE_QUANXField;

        private string xSTOBField;

        private string eAN_UPCField;

        private string dELIV_NUMB_TO_SEARCHField;

        private string dELIV_ITEM_TO_SEARCHField;

        private string sERIALNO_AUTO_NUMBERASSIGNMENTField;

        private string vENDRBATCHField;

        private string sTGE_TYPEField;

        private string sTGE_BINField;

        private string sU_PL_STCK_1Field;

        private string sT_UN_QTYY_1Field;

        private string sT_UN_QTYY_1_ISOField;

        private string uNITTYPE_1Field;

        private string sU_PL_STCK_2Field;

        private string sT_UN_QTYY_2Field;

        private string sT_UN_QTYY_2_ISOField;

        private string uNITTYPE_2Field;

        private string sTGE_TYPE_PCField;

        private string sTGE_BIN_PCField;

        private string nO_PST_CHGNTField;

        private string gR_NUMBERField;

        private string sTGE_TYPE_STField;

        private string sTGE_BIN_STField;

        private string mATDOC_TR_CANCELField;

        private string mATITEM_TR_CANCELField;

        private string mATYEAR_TR_CANCELField;

        private string nO_TRANSFER_REQField;

        private string cO_BUSPROCField;

        private string aCTTYPEField;

        private string sUPPL_VENDField;

        private string mATERIAL_EXTERNALField;

        private string mATERIAL_GUIDField;

        private string mATERIAL_VERSIONField;

        private string mOVE_MAT_EXTERNALField;

        private string mOVE_MAT_GUIDField;

        private string mOVE_MAT_VERSIONField;

        private string fUNC_AREAField;

        private string tR_PART_BAField;

        private string pAR_COMPCOField;

        private ZMBGMCR02_EXTNDE1BP2017_GM_ITEM_CREATE1 e1BP2017_GM_ITEM_CREATE1Field;

        private ZMBGMCR02_EXTNDZ1MBGMCR_ITEM_EXTND z1MBGMCR_ITEM_EXTNDField;

        private string sEGMENTField;

        public ZMBGMCR02_EXTNDE1BP2017_GM_ITEM_CREATE()
        {
            this.sEGMENTField = "1";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string MATERIAL
        {
            get
            {
                return this.mATERIALField;
            }
            set
            {
                this.mATERIALField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string PLANT
        {
            get
            {
                return this.pLANTField;
            }
            set
            {
                this.pLANTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string STGE_LOC
        {
            get
            {
                return this.sTGE_LOCField;
            }
            set
            {
                this.sTGE_LOCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string BATCH
        {
            get
            {
                return this.bATCHField;
            }
            set
            {
                this.bATCHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string MOVE_TYPE
        {
            get
            {
                return this.mOVE_TYPEField;
            }
            set
            {
                this.mOVE_TYPEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string STCK_TYPE
        {
            get
            {
                return this.sTCK_TYPEField;
            }
            set
            {
                this.sTCK_TYPEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string SPEC_STOCK
        {
            get
            {
                return this.sPEC_STOCKField;
            }
            set
            {
                this.sPEC_STOCKField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string VENDOR
        {
            get
            {
                return this.vENDORField;
            }
            set
            {
                this.vENDORField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string CUSTOMER
        {
            get
            {
                return this.cUSTOMERField;
            }
            set
            {
                this.cUSTOMERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public string SALES_ORD
        {
            get
            {
                return this.sALES_ORDField;
            }
            set
            {
                this.sALES_ORDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public string S_ORD_ITEM
        {
            get
            {
                return this.s_ORD_ITEMField;
            }
            set
            {
                this.s_ORD_ITEMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public string SCHED_LINE
        {
            get
            {
                return this.sCHED_LINEField;
            }
            set
            {
                this.sCHED_LINEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public string VAL_TYPE
        {
            get
            {
                return this.vAL_TYPEField;
            }
            set
            {
                this.vAL_TYPEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
        public string ENTRY_QNT
        {
            get
            {
                return this.eNTRY_QNTField;
            }
            set
            {
                this.eNTRY_QNTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 14)]
        public string ENTRY_UOM
        {
            get
            {
                return this.eNTRY_UOMField;
            }
            set
            {
                this.eNTRY_UOMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 15)]
        public string ENTRY_UOM_ISO
        {
            get
            {
                return this.eNTRY_UOM_ISOField;
            }
            set
            {
                this.eNTRY_UOM_ISOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 16)]
        public string PO_PR_QNT
        {
            get
            {
                return this.pO_PR_QNTField;
            }
            set
            {
                this.pO_PR_QNTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 17)]
        public string ORDERPR_UN
        {
            get
            {
                return this.oRDERPR_UNField;
            }
            set
            {
                this.oRDERPR_UNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 18)]
        public string ORDERPR_UN_ISO
        {
            get
            {
                return this.oRDERPR_UN_ISOField;
            }
            set
            {
                this.oRDERPR_UN_ISOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 19)]
        public string PO_NUMBER
        {
            get
            {
                return this.pO_NUMBERField;
            }
            set
            {
                this.pO_NUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 20)]
        public string PO_ITEM
        {
            get
            {
                return this.pO_ITEMField;
            }
            set
            {
                this.pO_ITEMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 21)]
        public string SHIPPING
        {
            get
            {
                return this.sHIPPINGField;
            }
            set
            {
                this.sHIPPINGField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 22)]
        public string COMP_SHIP
        {
            get
            {
                return this.cOMP_SHIPField;
            }
            set
            {
                this.cOMP_SHIPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 23)]
        public string NO_MORE_GR
        {
            get
            {
                return this.nO_MORE_GRField;
            }
            set
            {
                this.nO_MORE_GRField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 24)]
        public string ITEM_TEXT
        {
            get
            {
                return this.iTEM_TEXTField;
            }
            set
            {
                this.iTEM_TEXTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 25)]
        public string GR_RCPT
        {
            get
            {
                return this.gR_RCPTField;
            }
            set
            {
                this.gR_RCPTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 26)]
        public string UNLOAD_PT
        {
            get
            {
                return this.uNLOAD_PTField;
            }
            set
            {
                this.uNLOAD_PTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 27)]
        public string COSTCENTER
        {
            get
            {
                return this.cOSTCENTERField;
            }
            set
            {
                this.cOSTCENTERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 28)]
        public string ORDERID
        {
            get
            {
                return this.oRDERIDField;
            }
            set
            {
                this.oRDERIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 29)]
        public string ORDER_ITNO
        {
            get
            {
                return this.oRDER_ITNOField;
            }
            set
            {
                this.oRDER_ITNOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 30)]
        public string CALC_MOTIVE
        {
            get
            {
                return this.cALC_MOTIVEField;
            }
            set
            {
                this.cALC_MOTIVEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 31)]
        public string ASSET_NO
        {
            get
            {
                return this.aSSET_NOField;
            }
            set
            {
                this.aSSET_NOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 32)]
        public string SUB_NUMBER
        {
            get
            {
                return this.sUB_NUMBERField;
            }
            set
            {
                this.sUB_NUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 33)]
        public string RESERV_NO
        {
            get
            {
                return this.rESERV_NOField;
            }
            set
            {
                this.rESERV_NOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 34)]
        public string RES_ITEM
        {
            get
            {
                return this.rES_ITEMField;
            }
            set
            {
                this.rES_ITEMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 35)]
        public string RES_TYPE
        {
            get
            {
                return this.rES_TYPEField;
            }
            set
            {
                this.rES_TYPEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 36)]
        public string WITHDRAWN
        {
            get
            {
                return this.wITHDRAWNField;
            }
            set
            {
                this.wITHDRAWNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 37)]
        public string MOVE_MAT
        {
            get
            {
                return this.mOVE_MATField;
            }
            set
            {
                this.mOVE_MATField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 38)]
        public string MOVE_PLANT
        {
            get
            {
                return this.mOVE_PLANTField;
            }
            set
            {
                this.mOVE_PLANTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 39)]
        public string MOVE_STLOC
        {
            get
            {
                return this.mOVE_STLOCField;
            }
            set
            {
                this.mOVE_STLOCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 40)]
        public string MOVE_BATCH
        {
            get
            {
                return this.mOVE_BATCHField;
            }
            set
            {
                this.mOVE_BATCHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 41)]
        public string MOVE_VAL_TYPE
        {
            get
            {
                return this.mOVE_VAL_TYPEField;
            }
            set
            {
                this.mOVE_VAL_TYPEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 42)]
        public string MVT_IND
        {
            get
            {
                return this.mVT_INDField;
            }
            set
            {
                this.mVT_INDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 43)]
        public string MOVE_REAS
        {
            get
            {
                return this.mOVE_REASField;
            }
            set
            {
                this.mOVE_REASField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 44)]
        public string RL_EST_KEY
        {
            get
            {
                return this.rL_EST_KEYField;
            }
            set
            {
                this.rL_EST_KEYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 45)]
        public string REF_DATE
        {
            get
            {
                return this.rEF_DATEField;
            }
            set
            {
                this.rEF_DATEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 46)]
        public string COST_OBJ
        {
            get
            {
                return this.cOST_OBJField;
            }
            set
            {
                this.cOST_OBJField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 47)]
        public string PROFIT_SEGM_NO
        {
            get
            {
                return this.pROFIT_SEGM_NOField;
            }
            set
            {
                this.pROFIT_SEGM_NOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 48)]
        public string PROFIT_CTR
        {
            get
            {
                return this.pROFIT_CTRField;
            }
            set
            {
                this.pROFIT_CTRField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 49)]
        public string WBS_ELEM
        {
            get
            {
                return this.wBS_ELEMField;
            }
            set
            {
                this.wBS_ELEMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 50)]
        public string NETWORK
        {
            get
            {
                return this.nETWORKField;
            }
            set
            {
                this.nETWORKField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 51)]
        public string ACTIVITY
        {
            get
            {
                return this.aCTIVITYField;
            }
            set
            {
                this.aCTIVITYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 52)]
        public string PART_ACCT
        {
            get
            {
                return this.pART_ACCTField;
            }
            set
            {
                this.pART_ACCTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 53)]
        public string AMOUNT_LC
        {
            get
            {
                return this.aMOUNT_LCField;
            }
            set
            {
                this.aMOUNT_LCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 54)]
        public string AMOUNT_SV
        {
            get
            {
                return this.aMOUNT_SVField;
            }
            set
            {
                this.aMOUNT_SVField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 55)]
        public string REF_DOC_YR
        {
            get
            {
                return this.rEF_DOC_YRField;
            }
            set
            {
                this.rEF_DOC_YRField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 56)]
        public string REF_DOC
        {
            get
            {
                return this.rEF_DOCField;
            }
            set
            {
                this.rEF_DOCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 57)]
        public string REF_DOC_IT
        {
            get
            {
                return this.rEF_DOC_ITField;
            }
            set
            {
                this.rEF_DOC_ITField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 58)]
        public string EXPIRYDATE
        {
            get
            {
                return this.eXPIRYDATEField;
            }
            set
            {
                this.eXPIRYDATEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 59)]
        public string PROD_DATE
        {
            get
            {
                return this.pROD_DATEField;
            }
            set
            {
                this.pROD_DATEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 60)]
        public string FUND
        {
            get
            {
                return this.fUNDField;
            }
            set
            {
                this.fUNDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 61)]
        public string FUNDS_CTR
        {
            get
            {
                return this.fUNDS_CTRField;
            }
            set
            {
                this.fUNDS_CTRField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 62)]
        public string CMMT_ITEM
        {
            get
            {
                return this.cMMT_ITEMField;
            }
            set
            {
                this.cMMT_ITEMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 63)]
        public string VAL_SALES_ORD
        {
            get
            {
                return this.vAL_SALES_ORDField;
            }
            set
            {
                this.vAL_SALES_ORDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 64)]
        public string VAL_S_ORD_ITEM
        {
            get
            {
                return this.vAL_S_ORD_ITEMField;
            }
            set
            {
                this.vAL_S_ORD_ITEMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 65)]
        public string VAL_WBS_ELEM
        {
            get
            {
                return this.vAL_WBS_ELEMField;
            }
            set
            {
                this.vAL_WBS_ELEMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 66)]
        public string GL_ACCOUNT
        {
            get
            {
                return this.gL_ACCOUNTField;
            }
            set
            {
                this.gL_ACCOUNTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 67)]
        public string IND_PROPOSE_QUANX
        {
            get
            {
                return this.iND_PROPOSE_QUANXField;
            }
            set
            {
                this.iND_PROPOSE_QUANXField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 68)]
        public string XSTOB
        {
            get
            {
                return this.xSTOBField;
            }
            set
            {
                this.xSTOBField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 69)]
        public string EAN_UPC
        {
            get
            {
                return this.eAN_UPCField;
            }
            set
            {
                this.eAN_UPCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 70)]
        public string DELIV_NUMB_TO_SEARCH
        {
            get
            {
                return this.dELIV_NUMB_TO_SEARCHField;
            }
            set
            {
                this.dELIV_NUMB_TO_SEARCHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 71)]
        public string DELIV_ITEM_TO_SEARCH
        {
            get
            {
                return this.dELIV_ITEM_TO_SEARCHField;
            }
            set
            {
                this.dELIV_ITEM_TO_SEARCHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 72)]
        public string SERIALNO_AUTO_NUMBERASSIGNMENT
        {
            get
            {
                return this.sERIALNO_AUTO_NUMBERASSIGNMENTField;
            }
            set
            {
                this.sERIALNO_AUTO_NUMBERASSIGNMENTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 73)]
        public string VENDRBATCH
        {
            get
            {
                return this.vENDRBATCHField;
            }
            set
            {
                this.vENDRBATCHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 74)]
        public string STGE_TYPE
        {
            get
            {
                return this.sTGE_TYPEField;
            }
            set
            {
                this.sTGE_TYPEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 75)]
        public string STGE_BIN
        {
            get
            {
                return this.sTGE_BINField;
            }
            set
            {
                this.sTGE_BINField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 76)]
        public string SU_PL_STCK_1
        {
            get
            {
                return this.sU_PL_STCK_1Field;
            }
            set
            {
                this.sU_PL_STCK_1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 77)]
        public string ST_UN_QTYY_1
        {
            get
            {
                return this.sT_UN_QTYY_1Field;
            }
            set
            {
                this.sT_UN_QTYY_1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 78)]
        public string ST_UN_QTYY_1_ISO
        {
            get
            {
                return this.sT_UN_QTYY_1_ISOField;
            }
            set
            {
                this.sT_UN_QTYY_1_ISOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 79)]
        public string UNITTYPE_1
        {
            get
            {
                return this.uNITTYPE_1Field;
            }
            set
            {
                this.uNITTYPE_1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 80)]
        public string SU_PL_STCK_2
        {
            get
            {
                return this.sU_PL_STCK_2Field;
            }
            set
            {
                this.sU_PL_STCK_2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 81)]
        public string ST_UN_QTYY_2
        {
            get
            {
                return this.sT_UN_QTYY_2Field;
            }
            set
            {
                this.sT_UN_QTYY_2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 82)]
        public string ST_UN_QTYY_2_ISO
        {
            get
            {
                return this.sT_UN_QTYY_2_ISOField;
            }
            set
            {
                this.sT_UN_QTYY_2_ISOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 83)]
        public string UNITTYPE_2
        {
            get
            {
                return this.uNITTYPE_2Field;
            }
            set
            {
                this.uNITTYPE_2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 84)]
        public string STGE_TYPE_PC
        {
            get
            {
                return this.sTGE_TYPE_PCField;
            }
            set
            {
                this.sTGE_TYPE_PCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 85)]
        public string STGE_BIN_PC
        {
            get
            {
                return this.sTGE_BIN_PCField;
            }
            set
            {
                this.sTGE_BIN_PCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 86)]
        public string NO_PST_CHGNT
        {
            get
            {
                return this.nO_PST_CHGNTField;
            }
            set
            {
                this.nO_PST_CHGNTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 87)]
        public string GR_NUMBER
        {
            get
            {
                return this.gR_NUMBERField;
            }
            set
            {
                this.gR_NUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 88)]
        public string STGE_TYPE_ST
        {
            get
            {
                return this.sTGE_TYPE_STField;
            }
            set
            {
                this.sTGE_TYPE_STField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 89)]
        public string STGE_BIN_ST
        {
            get
            {
                return this.sTGE_BIN_STField;
            }
            set
            {
                this.sTGE_BIN_STField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 90)]
        public string MATDOC_TR_CANCEL
        {
            get
            {
                return this.mATDOC_TR_CANCELField;
            }
            set
            {
                this.mATDOC_TR_CANCELField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 91)]
        public string MATITEM_TR_CANCEL
        {
            get
            {
                return this.mATITEM_TR_CANCELField;
            }
            set
            {
                this.mATITEM_TR_CANCELField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 92)]
        public string MATYEAR_TR_CANCEL
        {
            get
            {
                return this.mATYEAR_TR_CANCELField;
            }
            set
            {
                this.mATYEAR_TR_CANCELField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 93)]
        public string NO_TRANSFER_REQ
        {
            get
            {
                return this.nO_TRANSFER_REQField;
            }
            set
            {
                this.nO_TRANSFER_REQField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 94)]
        public string CO_BUSPROC
        {
            get
            {
                return this.cO_BUSPROCField;
            }
            set
            {
                this.cO_BUSPROCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 95)]
        public string ACTTYPE
        {
            get
            {
                return this.aCTTYPEField;
            }
            set
            {
                this.aCTTYPEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 96)]
        public string SUPPL_VEND
        {
            get
            {
                return this.sUPPL_VENDField;
            }
            set
            {
                this.sUPPL_VENDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 97)]
        public string MATERIAL_EXTERNAL
        {
            get
            {
                return this.mATERIAL_EXTERNALField;
            }
            set
            {
                this.mATERIAL_EXTERNALField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 98)]
        public string MATERIAL_GUID
        {
            get
            {
                return this.mATERIAL_GUIDField;
            }
            set
            {
                this.mATERIAL_GUIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 99)]
        public string MATERIAL_VERSION
        {
            get
            {
                return this.mATERIAL_VERSIONField;
            }
            set
            {
                this.mATERIAL_VERSIONField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 100)]
        public string MOVE_MAT_EXTERNAL
        {
            get
            {
                return this.mOVE_MAT_EXTERNALField;
            }
            set
            {
                this.mOVE_MAT_EXTERNALField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 101)]
        public string MOVE_MAT_GUID
        {
            get
            {
                return this.mOVE_MAT_GUIDField;
            }
            set
            {
                this.mOVE_MAT_GUIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 102)]
        public string MOVE_MAT_VERSION
        {
            get
            {
                return this.mOVE_MAT_VERSIONField;
            }
            set
            {
                this.mOVE_MAT_VERSIONField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 103)]
        public string FUNC_AREA
        {
            get
            {
                return this.fUNC_AREAField;
            }
            set
            {
                this.fUNC_AREAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 104)]
        public string TR_PART_BA
        {
            get
            {
                return this.tR_PART_BAField;
            }
            set
            {
                this.tR_PART_BAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 105)]
        public string PAR_COMPCO
        {
            get
            {
                return this.pAR_COMPCOField;
            }
            set
            {
                this.pAR_COMPCOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 106)]
        public ZMBGMCR02_EXTNDE1BP2017_GM_ITEM_CREATE1 E1BP2017_GM_ITEM_CREATE1
        {
            get
            {
                return this.e1BP2017_GM_ITEM_CREATE1Field;
            }
            set
            {
                this.e1BP2017_GM_ITEM_CREATE1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 107)]
        public ZMBGMCR02_EXTNDZ1MBGMCR_ITEM_EXTND Z1MBGMCR_ITEM_EXTND
        {
            get
            {
                return this.z1MBGMCR_ITEM_EXTNDField;
            }
            set
            {
                this.z1MBGMCR_ITEM_EXTNDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SEGMENT
        {
            get
            {
                return this.sEGMENTField;
            }
            set
            {
                this.sEGMENTField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "ZMBGMCR02_EXTND.E1BP2017_GM_CODE")]
    public partial class ZMBGMCR02_EXTNDE1BP2017_GM_CODE
    {

        private string gM_CODEField;

        private string sEGMENTField;

        public ZMBGMCR02_EXTNDE1BP2017_GM_CODE()
        {
            this.sEGMENTField = "1";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string GM_CODE
        {
            get
            {
                return this.gM_CODEField;
            }
            set
            {
                this.gM_CODEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SEGMENT
        {
            get
            {
                return this.sEGMENTField;
            }
            set
            {
                this.sEGMENTField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "ZMBGMCR02_EXTND.E1BP2017_GM_HEAD_01")]
    public partial class ZMBGMCR02_EXTNDE1BP2017_GM_HEAD_01
    {

        private string pSTNG_DATEField;

        private string dOC_DATEField;

        private string rEF_DOC_NOField;

        private string bILL_OF_LADINGField;

        private string gR_GI_SLIP_NOField;

        private string pR_UNAMEField;

        private string hEADER_TXTField;

        private string vER_GR_GI_SLIPField;

        private string vER_GR_GI_SLIPXField;

        private string eXT_WMSField;

        private string rEF_DOC_NO_LONGField;

        private string bILL_OF_LADING_LONGField;

        private string bAR_CODEField;

        private string sEGMENTField;

        public ZMBGMCR02_EXTNDE1BP2017_GM_HEAD_01()
        {
            this.sEGMENTField = "1";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string PSTNG_DATE
        {
            get
            {
                return this.pSTNG_DATEField;
            }
            set
            {
                this.pSTNG_DATEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string DOC_DATE
        {
            get
            {
                return this.dOC_DATEField;
            }
            set
            {
                this.dOC_DATEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string REF_DOC_NO
        {
            get
            {
                return this.rEF_DOC_NOField;
            }
            set
            {
                this.rEF_DOC_NOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string BILL_OF_LADING
        {
            get
            {
                return this.bILL_OF_LADINGField;
            }
            set
            {
                this.bILL_OF_LADINGField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string GR_GI_SLIP_NO
        {
            get
            {
                return this.gR_GI_SLIP_NOField;
            }
            set
            {
                this.gR_GI_SLIP_NOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string PR_UNAME
        {
            get
            {
                return this.pR_UNAMEField;
            }
            set
            {
                this.pR_UNAMEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string HEADER_TXT
        {
            get
            {
                return this.hEADER_TXTField;
            }
            set
            {
                this.hEADER_TXTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string VER_GR_GI_SLIP
        {
            get
            {
                return this.vER_GR_GI_SLIPField;
            }
            set
            {
                this.vER_GR_GI_SLIPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string VER_GR_GI_SLIPX
        {
            get
            {
                return this.vER_GR_GI_SLIPXField;
            }
            set
            {
                this.vER_GR_GI_SLIPXField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public string EXT_WMS
        {
            get
            {
                return this.eXT_WMSField;
            }
            set
            {
                this.eXT_WMSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public string REF_DOC_NO_LONG
        {
            get
            {
                return this.rEF_DOC_NO_LONGField;
            }
            set
            {
                this.rEF_DOC_NO_LONGField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public string BILL_OF_LADING_LONG
        {
            get
            {
                return this.bILL_OF_LADING_LONGField;
            }
            set
            {
                this.bILL_OF_LADING_LONGField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public string BAR_CODE
        {
            get
            {
                return this.bAR_CODEField;
            }
            set
            {
                this.bAR_CODEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SEGMENT
        {
            get
            {
                return this.sEGMENTField;
            }
            set
            {
                this.sEGMENTField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "ZMBGMCR02_EXTND.E1MBGMCR")]
    public partial class ZMBGMCR02_EXTNDE1MBGMCR
    {

        private string tESTRUNField;

        private string sEGMENTField;

        public ZMBGMCR02_EXTNDE1MBGMCR()
        {
            this.sEGMENTField = "1";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string TESTRUN
        {
            get
            {
                return this.tESTRUNField;
            }
            set
            {
                this.tESTRUNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SEGMENT
        {
            get
            {
                return this.sEGMENTField;
            }
            set
            {
                this.sEGMENTField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ZMBGMCR02_EXTND_OB_Async_MI1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public ZMBGMCR02_EXTND ZMBGMCR02_EXTND;

        public ZMBGMCR02_EXTND_OB_Async_MI1()
        {
        }

        public ZMBGMCR02_EXTND_OB_Async_MI1(ZMBGMCR02_EXTND ZMBGMCR02_EXTND)
        {
            this.ZMBGMCR02_EXTND = ZMBGMCR02_EXTND;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZMBGMCR02_EXTND_OB_Async_MIChannel : ZMBGMCR02_EXTND_OB_Async_MI, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZMBGMCR02_EXTND_OB_Async_MIClient : System.ServiceModel.ClientBase<ZMBGMCR02_EXTND_OB_Async_MI>, ZMBGMCR02_EXTND_OB_Async_MI
    {

        public ZMBGMCR02_EXTND_OB_Async_MIClient()
        {
        }

        public ZMBGMCR02_EXTND_OB_Async_MIClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public ZMBGMCR02_EXTND_OB_Async_MIClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public ZMBGMCR02_EXTND_OB_Async_MIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public ZMBGMCR02_EXTND_OB_Async_MIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ZMBGMCR02_EXTND_OB_Async_MI.ZMBGMCR02_EXTND_OB_Async_MI(ZMBGMCR02_EXTND_OB_Async_MI1 request)
        {
            base.Channel.ZMBGMCR02_EXTND_OB_Async_MI(request);
        }

        public void ZMBGMCR02_EXTND_OB_Async_MI(ZMBGMCR02_EXTND ZMBGMCR02_EXTND)
        {
            ZMBGMCR02_EXTND_OB_Async_MI1 inValue = new ZMBGMCR02_EXTND_OB_Async_MI1();
            inValue.ZMBGMCR02_EXTND = ZMBGMCR02_EXTND;
            ((ZMBGMCR02_EXTND_OB_Async_MI)(this)).ZMBGMCR02_EXTND_OB_Async_MI(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ZMBGMCR02_EXTND_OB_Async_MI.BeginZMBGMCR02_EXTND_OB_Async_MI(ZMBGMCR02_EXTND_OB_Async_MI1 request, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginZMBGMCR02_EXTND_OB_Async_MI(request, callback, asyncState);
        }

        public System.IAsyncResult BeginZMBGMCR02_EXTND_OB_Async_MI(ZMBGMCR02_EXTND ZMBGMCR02_EXTND, System.AsyncCallback callback, object asyncState)
        {
            ZMBGMCR02_EXTND_OB_Async_MI1 inValue = new ZMBGMCR02_EXTND_OB_Async_MI1();
            inValue.ZMBGMCR02_EXTND = ZMBGMCR02_EXTND;
            return ((ZMBGMCR02_EXTND_OB_Async_MI)(this)).BeginZMBGMCR02_EXTND_OB_Async_MI(inValue, callback, asyncState);
        }

        public void EndZMBGMCR02_EXTND_OB_Async_MI(System.IAsyncResult result)
        {
            base.Channel.EndZMBGMCR02_EXTND_OB_Async_MI(result);
        }
    }