// CRITICAL: Do not change the location of this files. It is duplicated in the Test-Harness. //
// CRITICAl: Do not change the namespace of any code within this file in any way. //   

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "sap-com:XI.interfaces:utils", ConfigurationName = "SYSTAT01_OB_Async_MI")]
public interface SYSTAT01_OB_Async_MI
{

    // CODEGEN: Generating message contract since the operation SYSTAT01_OB_Async_MI is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://sap.com/xi/WebService/soap1.1")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    void SYSTAT01_OB_Async_MI(SYSTAT01_OB_Async_MI1 request);

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, AsyncPattern = true, Action = "http://sap.com/xi/WebService/soap1.1")]
    System.IAsyncResult BeginSYSTAT01_OB_Async_MI(SYSTAT01_OB_Async_MI1 request, System.AsyncCallback callback, object asyncState);

    void EndSYSTAT01_OB_Async_MI(System.IAsyncResult result);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class SYSTAT01
{

    private STATUSSYSTAT01 iDOCField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public STATUSSYSTAT01 IDOC
    {
        get
        {
            return this.iDOCField;
        }
        set
        {
            this.iDOCField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "STATUS.SYSTAT01")]
public partial class STATUSSYSTAT01
{

    private EDI_DC40STATUSSYSTAT01 eDI_DC40Field;

    private SYSTAT01E1STATS[] e1STATSField;

    private string bEGINField;

    public STATUSSYSTAT01()
    {
        this.bEGINField = "1";
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public EDI_DC40STATUSSYSTAT01 EDI_DC40
    {
        get
        {
            return this.eDI_DC40Field;
        }
        set
        {
            this.eDI_DC40Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("E1STATS", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public SYSTAT01E1STATS[] E1STATS
    {
        get
        {
            return this.e1STATSField;
        }
        set
        {
            this.e1STATSField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string BEGIN
    {
        get
        {
            return this.bEGINField;
        }
        set
        {
            this.bEGINField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "EDI_DC40.STATUS.SYSTAT01")]
public partial class EDI_DC40STATUSSYSTAT01
{

    private string tABNAMField;

    private string mANDTField;

    private string dOCNUMField;

    private string dOCRELField;

    private string sTATUSField;

    private EDI_DC40STATUSSYSTAT01DIRECT dIRECTField;

    private string oUTMODField;

    private string eXPRSSField;

    private string tESTField;

    private string iDOCTYPField;

    private string cIMTYPField;

    private string mESTYPField;

    private string mESCODField;

    private string mESFCTField;

    private string sTDField;

    private string sTDVRSField;

    private string sTDMESField;

    private string sNDPORField;

    private string sNDPRTField;

    private string sNDPFCField;

    private string sNDPRNField;

    private string sNDSADField;

    private string sNDLADField;

    private string rCVPORField;

    private string rCVPRTField;

    private string rCVPFCField;

    private string rCVPRNField;

    private string rCVSADField;

    private string rCVLADField;

    private string cREDATField;

    private string cRETIMField;

    private string rEFINTField;

    private string rEFGRPField;

    private string rEFMESField;

    private string aRCKEYField;

    private string sERIALField;

    private string sEGMENTField;

    public EDI_DC40STATUSSYSTAT01()
    {
        this.tABNAMField = "EDI_DC40";
        this.iDOCTYPField = "SYSTAT01";
        this.mESTYPField = "STATUS";
        this.sEGMENTField = "1";
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string TABNAM
    {
        get
        {
            return this.tABNAMField;
        }
        set
        {
            this.tABNAMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string MANDT
    {
        get
        {
            return this.mANDTField;
        }
        set
        {
            this.mANDTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
    public string DOCNUM
    {
        get
        {
            return this.dOCNUMField;
        }
        set
        {
            this.dOCNUMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
    public string DOCREL
    {
        get
        {
            return this.dOCRELField;
        }
        set
        {
            this.dOCRELField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
    public string STATUS
    {
        get
        {
            return this.sTATUSField;
        }
        set
        {
            this.sTATUSField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
    public EDI_DC40STATUSSYSTAT01DIRECT DIRECT
    {
        get
        {
            return this.dIRECTField;
        }
        set
        {
            this.dIRECTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
    public string OUTMOD
    {
        get
        {
            return this.oUTMODField;
        }
        set
        {
            this.oUTMODField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
    public string EXPRSS
    {
        get
        {
            return this.eXPRSSField;
        }
        set
        {
            this.eXPRSSField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
    public string TEST
    {
        get
        {
            return this.tESTField;
        }
        set
        {
            this.tESTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
    public string IDOCTYP
    {
        get
        {
            return this.iDOCTYPField;
        }
        set
        {
            this.iDOCTYPField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
    public string CIMTYP
    {
        get
        {
            return this.cIMTYPField;
        }
        set
        {
            this.cIMTYPField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
    public string MESTYP
    {
        get
        {
            return this.mESTYPField;
        }
        set
        {
            this.mESTYPField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
    public string MESCOD
    {
        get
        {
            return this.mESCODField;
        }
        set
        {
            this.mESCODField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
    public string MESFCT
    {
        get
        {
            return this.mESFCTField;
        }
        set
        {
            this.mESFCTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 14)]
    public string STD
    {
        get
        {
            return this.sTDField;
        }
        set
        {
            this.sTDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 15)]
    public string STDVRS
    {
        get
        {
            return this.sTDVRSField;
        }
        set
        {
            this.sTDVRSField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 16)]
    public string STDMES
    {
        get
        {
            return this.sTDMESField;
        }
        set
        {
            this.sTDMESField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 17)]
    public string SNDPOR
    {
        get
        {
            return this.sNDPORField;
        }
        set
        {
            this.sNDPORField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 18)]
    public string SNDPRT
    {
        get
        {
            return this.sNDPRTField;
        }
        set
        {
            this.sNDPRTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 19)]
    public string SNDPFC
    {
        get
        {
            return this.sNDPFCField;
        }
        set
        {
            this.sNDPFCField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 20)]
    public string SNDPRN
    {
        get
        {
            return this.sNDPRNField;
        }
        set
        {
            this.sNDPRNField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 21)]
    public string SNDSAD
    {
        get
        {
            return this.sNDSADField;
        }
        set
        {
            this.sNDSADField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 22)]
    public string SNDLAD
    {
        get
        {
            return this.sNDLADField;
        }
        set
        {
            this.sNDLADField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 23)]
    public string RCVPOR
    {
        get
        {
            return this.rCVPORField;
        }
        set
        {
            this.rCVPORField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 24)]
    public string RCVPRT
    {
        get
        {
            return this.rCVPRTField;
        }
        set
        {
            this.rCVPRTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 25)]
    public string RCVPFC
    {
        get
        {
            return this.rCVPFCField;
        }
        set
        {
            this.rCVPFCField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 26)]
    public string RCVPRN
    {
        get
        {
            return this.rCVPRNField;
        }
        set
        {
            this.rCVPRNField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 27)]
    public string RCVSAD
    {
        get
        {
            return this.rCVSADField;
        }
        set
        {
            this.rCVSADField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 28)]
    public string RCVLAD
    {
        get
        {
            return this.rCVLADField;
        }
        set
        {
            this.rCVLADField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 29)]
    public string CREDAT
    {
        get
        {
            return this.cREDATField;
        }
        set
        {
            this.cREDATField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 30)]
    public string CRETIM
    {
        get
        {
            return this.cRETIMField;
        }
        set
        {
            this.cRETIMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 31)]
    public string REFINT
    {
        get
        {
            return this.rEFINTField;
        }
        set
        {
            this.rEFINTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 32)]
    public string REFGRP
    {
        get
        {
            return this.rEFGRPField;
        }
        set
        {
            this.rEFGRPField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 33)]
    public string REFMES
    {
        get
        {
            return this.rEFMESField;
        }
        set
        {
            this.rEFMESField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 34)]
    public string ARCKEY
    {
        get
        {
            return this.aRCKEYField;
        }
        set
        {
            this.aRCKEYField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 35)]
    public string SERIAL
    {
        get
        {
            return this.sERIALField;
        }
        set
        {
            this.sERIALField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SEGMENT
    {
        get
        {
            return this.sEGMENTField;
        }
        set
        {
            this.sEGMENTField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public enum EDI_DC40STATUSSYSTAT01DIRECT
{

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "SYSTAT01.E1STATS")]
public partial class SYSTAT01E1STATS
{

    private string tABNAMField;

    private string mANDTField;

    private string dOCNUMField;

    private string lOGDATField;

    private string lOGTIMField;

    private string sTATUSField;

    private string uNAMEField;

    private string rEPIDField;

    private string rOUTIDField;

    private string sTACODField;

    private string sTATXTField;

    private string sEGNUMField;

    private string sEGFLDField;

    private string sTAPA1Field;

    private string sTAPA2Field;

    private string sTAPA3Field;

    private string sTAPA4Field;

    private string rEFINTField;

    private string rEFGRPField;

    private string rEFMESField;

    private string aRCKEYField;

    private string sTATYPField;

    private string sTAMQUField;

    private string sTAMIDField;

    private string sTAMNOField;

    private string sEGMENTField;

    public SYSTAT01E1STATS()
    {
        this.sEGMENTField = "1";
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string TABNAM
    {
        get
        {
            return this.tABNAMField;
        }
        set
        {
            this.tABNAMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string MANDT
    {
        get
        {
            return this.mANDTField;
        }
        set
        {
            this.mANDTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
    public string DOCNUM
    {
        get
        {
            return this.dOCNUMField;
        }
        set
        {
            this.dOCNUMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
    public string LOGDAT
    {
        get
        {
            return this.lOGDATField;
        }
        set
        {
            this.lOGDATField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
    public string LOGTIM
    {
        get
        {
            return this.lOGTIMField;
        }
        set
        {
            this.lOGTIMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
    public string STATUS
    {
        get
        {
            return this.sTATUSField;
        }
        set
        {
            this.sTATUSField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
    public string UNAME
    {
        get
        {
            return this.uNAMEField;
        }
        set
        {
            this.uNAMEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
    public string REPID
    {
        get
        {
            return this.rEPIDField;
        }
        set
        {
            this.rEPIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
    public string ROUTID
    {
        get
        {
            return this.rOUTIDField;
        }
        set
        {
            this.rOUTIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
    public string STACOD
    {
        get
        {
            return this.sTACODField;
        }
        set
        {
            this.sTACODField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
    public string STATXT
    {
        get
        {
            return this.sTATXTField;
        }
        set
        {
            this.sTATXTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
    public string SEGNUM
    {
        get
        {
            return this.sEGNUMField;
        }
        set
        {
            this.sEGNUMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
    public string SEGFLD
    {
        get
        {
            return this.sEGFLDField;
        }
        set
        {
            this.sEGFLDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
    public string STAPA1
    {
        get
        {
            return this.sTAPA1Field;
        }
        set
        {
            this.sTAPA1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 14)]
    public string STAPA2
    {
        get
        {
            return this.sTAPA2Field;
        }
        set
        {
            this.sTAPA2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 15)]
    public string STAPA3
    {
        get
        {
            return this.sTAPA3Field;
        }
        set
        {
            this.sTAPA3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 16)]
    public string STAPA4
    {
        get
        {
            return this.sTAPA4Field;
        }
        set
        {
            this.sTAPA4Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 17)]
    public string REFINT
    {
        get
        {
            return this.rEFINTField;
        }
        set
        {
            this.rEFINTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 18)]
    public string REFGRP
    {
        get
        {
            return this.rEFGRPField;
        }
        set
        {
            this.rEFGRPField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 19)]
    public string REFMES
    {
        get
        {
            return this.rEFMESField;
        }
        set
        {
            this.rEFMESField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 20)]
    public string ARCKEY
    {
        get
        {
            return this.aRCKEYField;
        }
        set
        {
            this.aRCKEYField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 21)]
    public string STATYP
    {
        get
        {
            return this.sTATYPField;
        }
        set
        {
            this.sTATYPField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 22)]
    public string STAMQU
    {
        get
        {
            return this.sTAMQUField;
        }
        set
        {
            this.sTAMQUField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 23)]
    public string STAMID
    {
        get
        {
            return this.sTAMIDField;
        }
        set
        {
            this.sTAMIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 24)]
    public string STAMNO
    {
        get
        {
            return this.sTAMNOField;
        }
        set
        {
            this.sTAMNOField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SEGMENT
    {
        get
        {
            return this.sEGMENTField;
        }
        set
        {
            this.sEGMENTField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class SYSTAT01_OB_Async_MI1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
    public SYSTAT01 SYSTAT01;

    public SYSTAT01_OB_Async_MI1()
    {
    }

    public SYSTAT01_OB_Async_MI1(SYSTAT01 SYSTAT01)
    {
        this.SYSTAT01 = SYSTAT01;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface SYSTAT01_OB_Async_MIChannel : SYSTAT01_OB_Async_MI, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SYSTAT01_OB_Async_MIClient : System.ServiceModel.ClientBase<SYSTAT01_OB_Async_MI>, SYSTAT01_OB_Async_MI
{

    public SYSTAT01_OB_Async_MIClient()
    {
    }

    public SYSTAT01_OB_Async_MIClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public SYSTAT01_OB_Async_MIClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public SYSTAT01_OB_Async_MIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public SYSTAT01_OB_Async_MIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    void SYSTAT01_OB_Async_MI.SYSTAT01_OB_Async_MI(SYSTAT01_OB_Async_MI1 request)
    {
        base.Channel.SYSTAT01_OB_Async_MI(request);
    }

    public void SYSTAT01_OB_Async_MI(SYSTAT01 SYSTAT01)
    {
        SYSTAT01_OB_Async_MI1 inValue = new SYSTAT01_OB_Async_MI1();
        inValue.SYSTAT01 = SYSTAT01;
        ((SYSTAT01_OB_Async_MI)(this)).SYSTAT01_OB_Async_MI(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult SYSTAT01_OB_Async_MI.BeginSYSTAT01_OB_Async_MI(SYSTAT01_OB_Async_MI1 request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginSYSTAT01_OB_Async_MI(request, callback, asyncState);
    }

    public System.IAsyncResult BeginSYSTAT01_OB_Async_MI(SYSTAT01 SYSTAT01, System.AsyncCallback callback, object asyncState)
    {
        SYSTAT01_OB_Async_MI1 inValue = new SYSTAT01_OB_Async_MI1();
        inValue.SYSTAT01 = SYSTAT01;
        return ((SYSTAT01_OB_Async_MI)(this)).BeginSYSTAT01_OB_Async_MI(inValue, callback, asyncState);
    }

    public void EndSYSTAT01_OB_Async_MI(System.IAsyncResult result)
    {
        base.Channel.EndSYSTAT01_OB_Async_MI(result);
    }
}